### ISSUE TITLE
US Payroll

### ISSUE THREAD

**Issue by max3903** [OCA/l10n-usa#16]
Question has been asked on the community mailing list here:
https://www.odoo.com/groups/community-59/community-31930496

Feel free to add your feedbacks on the subject here.

**Comment by brian10048** [comment]
@max3903 

@jaredkipe has a pretty solid solution for this here: https://github.com/hibou-io/hibou-odoo-suite/tree/12.0/l10n_us_hr_payroll  Maybe he wouldn't mind if we put it into the OCA?

I've been using v11 for a while and the v12 seems to be working well in testing for me.  There are several US state localizations in that repo as well.

**Comment by max3903** [comment]
@brian10048 Do you mind asking them?

**Comment by jaredkipe** [comment]
@max3903 
@brian10048 

Why does it have to be **in the OCA**?

This code is licensed AGPL3 and includes many useful things such as the ability to get Attendances, Timesheets, Holidays/Leaves, and Gamification badges onto payslips.

While I appreciate what the OCA does, and do a bit of maintenance as well, I will not be putting my code into the OCA.  This is simply not how I want to maintain software that I, and my clients, use. (e.g. https://github.com/OCA/stock-logistics-warehouse/pull/586 )

FWIW we have recently added 5 new states that are going through our testing pipeline now:
- Arkansas
- Iowa
- Michigan
- Minnesota
- South Carolina

You can find them in various branches or getting merged and tested over here. https://gitlab.com/hibou-io/hibou-odoo/suite/tree/11.0-test

**Comment by rvalyi** [comment]
`While I appreciate what the OCA does, and do a bit of maintenance as well, I will not be putting my code into the OCA. This is simply not how I want to maintain software that I, and my clients, use. (e.g. OCA/stock-logistics-warehouse#586 )`

@jaredkipe could you elaborate please? Is it because doing things in the OCA is slower due to the review process? If this is the reason, you can do what we do at Akretion and many other prominent integrators: we actually deploy our own OCA forks at the customers. We want the best of the two worlds: doing that we are able to hot deploy any fix we want with no delay.
Meanwhile, we still try to contrib such central things in the OCA to increase the synergy.
Bare in mind the central Odoo payroll module is EE starting from Odoo 13. A community solution based on https://github.com/OCA/payroll will only make it with a large community, so I think every bit like the US payroll localization will make a difference.

Finally another strategy we use at Akretion is to make things very modular in a way we can easily push some basic modules in the OCA and keep the more specific and less structuring modules that only our own customers are likely to fund on github.com/akretion.

**Comment by max3903** [comment]
> Why does it have to be **in the OCA**?

It doesn't... Your choice.

On top of @rvalyi comments, my experience is that by having your modules in the OCA, you get more visibility and OCA contributions. If someone else comes with modules for the same requirements, they will set the reference. It's much more work to arrive second and deal with a module already there. You kind of need to converge.

**Comment by max3903** [comment]
Not to mention that we can add you in the US localization PSC to have write access to the repo and you can set your module as beta:
https://odoo-community.org/page/module-maturity-levels
